### ISSUE TITLE
The Lite branch should install 4.3 OC CLI and the IGC CLI

### ISSUE THREAD

**Issue by mjperrins** [cloud-native-toolkit/image-cli-tools#7]
The Lite branch should install 4.3 OC CLI and the IGC CLI

**Comment by seansund** [comment]
I've worked to remove as much as possible from the cli-tools image so that we don't require a 2+ GB download in order to run iZero. `oc` is currently part of the image (although a little hacking was required to get it to run on Alpine) but npm and the igc cli have been removed since they are not needed by the terraform modules.

We may need to revisit the purpose of the cli-tools image and perhaps split it into two different images 

- one with minimal tools to support iZero installs
- a `kitchen sink` image that can support end-to-end SDLC activities

Could you reword this in the form of a story? What are you trying to do? Why do you need those?
